apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapi-ingress
spec:
  rules:
    - host: <example.com>
      http:
        paths:
          - pathType: Prefix
            path: /products
            backend:
              service:
                name: sapi-loadbalancer-service
                port:
                  number: 80
