apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: sapi-products 
  POSTGRES_USER: sapi-user
  POSTGRES_PASSWORD: t%8!pD9J7;1~`ZKecag@6lEZrga=H=n)P4jy<K=&
